- name: Copy file to targeta
  hosts: all
  vars:
    dest_file: test-cond.txt
    line1: Ubuntu
    line2: CentOS
  vars_files:
    - vars.yml
  tasks:
    - name: 1. Create a file
      file:
        path: ~/ansible_test/{{dest_file}}
        state: touch

    - name: 2. Update file for Debian
      lineinfile:
        path: ~/ansible_test/{{dest_file}}
        line: 'Linux distribution  {{line1}}'
      when: ansible_os_family=="Debian"

    - name: 3. Update file for CentOS
      lineinfile:
        path: ~/ansible_test/{{dest_file}}
        line: 'Linux distribution  {{line2}}'
      when: ansible_os_family=="RedHat"