- name: Copy file to targeta
  hosts: all
  tasks:
    - name: 1. Create a folder
      file:
        path: ~/ansible_test
        state: directory
    - name: 2. Copy file
      copy:
        src: /tmp/test-copy.txt
        dest: ~/ansible_test/test-copy.txt
    - name: 3. Add a line to file
      lineinfile:
        path: ~/ansible_test/test-copy.txt
        line: 'Line will be added just one time even if you run a playbook a few times'
