- name: Copy file to targeta
  hosts: all
  vars:
    dest_file: test-conditions.txt
    line1: Test line1
    line2: Test line2
  vars_files:
    - vars.yml
  tasks:
    - name: 1. Create a file
      file:
        path: ~/ansible_test/{{dest_file}}
        state: file
    - name: 3. Add a line1 to file
      lineinfile:
        path: ~/ansible_test/{{dest_file}}
        line: 'Added line:  {{line1}}'
    - name: 4. Add a line2 to file
      lineinfile:
        path: ~/ansible_test/{{dest_file}}
        line: 'Added line:  {{line2}}'
